// Generated by CIRCT firtool-1.62.0
module cell_0(
  input         clock,
                reset,
  input  [15:0] io_lane_in_1,
                io_lane_in_2,
                io_stage_in_1,
                io_cell_mode,
  input         io_lane_out_1_select,
  output [15:0] io_lane_out_1,
                io_lane_out_2,
                io_stage_out_1,
                io_accum_out
);

  reg [15:0] lane_out_1_reg;
  reg [15:0] lane_out_2_reg;
  reg [15:0] stage_out_1_reg;
  reg [15:0] accum_reg;
  reg [15:0] accum_out_reg;
  always @(posedge clock) begin
    if (reset) begin
      lane_out_1_reg <= 16'h0;
      lane_out_2_reg <= 16'h0;
      stage_out_1_reg <= 16'h0;
      accum_reg <= 16'h0;
      accum_out_reg <= 16'h0;
    end
    else if (io_cell_mode == 16'h0) begin
      lane_out_1_reg <= io_lane_in_1;
      stage_out_1_reg <= io_stage_in_1;
      accum_reg <= io_lane_in_1 * io_stage_in_1 + accum_reg;
      accum_out_reg <= accum_reg;
    end
    else if (io_cell_mode == 16'h1) begin
      lane_out_1_reg <= io_lane_out_1_select ? io_lane_in_1 : io_lane_in_2;
      lane_out_2_reg <= 16'h0;
    end
    else if (io_cell_mode == 16'h2) begin
      lane_out_1_reg <= io_lane_out_1_select ? io_lane_in_1 : io_lane_in_2;
      lane_out_2_reg <= io_lane_in_1;
    end
    else if (io_cell_mode == 16'h3) begin
      lane_out_1_reg <= io_lane_out_1_select ? io_lane_in_1 : io_lane_in_2;
      lane_out_2_reg <= 16'h0;
    end
    else if (io_cell_mode == 16'h4) begin
      lane_out_1_reg <= io_lane_out_1_select ? io_lane_in_1 : io_lane_in_2;
      lane_out_2_reg <= io_lane_in_2;
    end
    else if (io_cell_mode == 16'h5) begin
      lane_out_1_reg <= io_lane_out_1_select ? io_lane_in_1 : io_lane_in_2;
      lane_out_2_reg <= io_lane_in_1 * io_lane_in_2;
    end
    else if (io_cell_mode == 16'h6) begin
      lane_out_1_reg <= io_lane_out_1_select ? io_lane_in_1 : io_lane_in_2;
      lane_out_2_reg <= io_lane_in_1 + io_lane_in_2;
    end
    else if (io_cell_mode == 16'h7) begin
      lane_out_1_reg <= io_lane_out_1_select ? io_lane_in_1 : io_lane_in_2;
      lane_out_2_reg <= io_lane_in_2;
    end
    else if (io_cell_mode == 16'h8) begin
      lane_out_1_reg <= io_lane_out_1_select ? io_lane_in_1 : io_lane_in_2;
      lane_out_2_reg <= io_lane_in_1;
    end
  end // always @(posedge)
  assign io_lane_out_1 = lane_out_1_reg;
  assign io_lane_out_2 = lane_out_2_reg;
  assign io_stage_out_1 = stage_out_1_reg;
  assign io_accum_out = accum_out_reg;
endmodule

module baseline_pcu_8x6(
  input         clock,
                reset,
  input  [15:0] io_lane_in_1_0,
                io_lane_in_1_1,
                io_lane_in_1_2,
                io_lane_in_1_3,
                io_lane_in_1_4,
                io_lane_in_1_5,
                io_lane_in_1_6,
                io_lane_in_1_7,
                io_lane_in_2_0,
                io_lane_in_2_1,
                io_lane_in_2_2,
                io_lane_in_2_3,
                io_lane_in_2_4,
                io_lane_in_2_5,
                io_lane_in_2_6,
                io_lane_in_2_7,
                io_stage_in_1_0,
                io_stage_in_1_1,
                io_stage_in_1_2,
                io_stage_in_1_3,
                io_stage_in_1_4,
                io_stage_in_1_5,
                io_cell_mode_0,
                io_cell_mode_1,
                io_cell_mode_2,
                io_cell_mode_3,
                io_cell_mode_4,
                io_cell_mode_5,
                io_cell_mode_6,
                io_cell_mode_7,
                io_cell_mode_8,
                io_cell_mode_9,
                io_cell_mode_10,
                io_cell_mode_11,
                io_cell_mode_12,
                io_cell_mode_13,
                io_cell_mode_14,
                io_cell_mode_15,
                io_cell_mode_16,
                io_cell_mode_17,
                io_cell_mode_18,
                io_cell_mode_19,
                io_cell_mode_20,
                io_cell_mode_21,
                io_cell_mode_22,
                io_cell_mode_23,
                io_cell_mode_24,
                io_cell_mode_25,
                io_cell_mode_26,
                io_cell_mode_27,
                io_cell_mode_28,
                io_cell_mode_29,
                io_cell_mode_30,
                io_cell_mode_31,
                io_cell_mode_32,
                io_cell_mode_33,
                io_cell_mode_34,
                io_cell_mode_35,
                io_cell_mode_36,
                io_cell_mode_37,
                io_cell_mode_38,
                io_cell_mode_39,
                io_cell_mode_40,
                io_cell_mode_41,
                io_cell_mode_42,
                io_cell_mode_43,
                io_cell_mode_44,
                io_cell_mode_45,
                io_cell_mode_46,
                io_cell_mode_47,
  input         io_lane_out_1_select_0,
                io_lane_out_1_select_1,
                io_lane_out_1_select_2,
                io_lane_out_1_select_3,
                io_lane_out_1_select_4,
                io_lane_out_1_select_5,
                io_lane_out_1_select_6,
                io_lane_out_1_select_7,
                io_lane_out_1_select_8,
                io_lane_out_1_select_9,
                io_lane_out_1_select_10,
                io_lane_out_1_select_11,
                io_lane_out_1_select_12,
                io_lane_out_1_select_13,
                io_lane_out_1_select_14,
                io_lane_out_1_select_15,
                io_lane_out_1_select_16,
                io_lane_out_1_select_17,
                io_lane_out_1_select_18,
                io_lane_out_1_select_19,
                io_lane_out_1_select_20,
                io_lane_out_1_select_21,
                io_lane_out_1_select_22,
                io_lane_out_1_select_23,
                io_lane_out_1_select_24,
                io_lane_out_1_select_25,
                io_lane_out_1_select_26,
                io_lane_out_1_select_27,
                io_lane_out_1_select_28,
                io_lane_out_1_select_29,
                io_lane_out_1_select_30,
                io_lane_out_1_select_31,
                io_lane_out_1_select_32,
                io_lane_out_1_select_33,
                io_lane_out_1_select_34,
                io_lane_out_1_select_35,
                io_lane_out_1_select_36,
                io_lane_out_1_select_37,
                io_lane_out_1_select_38,
                io_lane_out_1_select_39,
                io_lane_out_1_select_40,
                io_lane_out_1_select_41,
                io_lane_out_1_select_42,
                io_lane_out_1_select_43,
                io_lane_out_1_select_44,
                io_lane_out_1_select_45,
                io_lane_out_1_select_46,
                io_lane_out_1_select_47,
                io_select_0,
                io_select_1,
                io_select_2,
                io_select_3,
                io_select_4,
                io_select_5,
                io_select_6,
  output [15:0] io_lane_out_1_0,
                io_lane_out_1_1,
                io_lane_out_1_2,
                io_lane_out_1_3,
                io_lane_out_1_4,
                io_lane_out_1_5,
                io_lane_out_1_6,
                io_lane_out_1_7,
                io_lane_out_2_0,
                io_lane_out_2_1,
                io_lane_out_2_2,
                io_lane_out_2_3,
                io_lane_out_2_4,
                io_lane_out_2_5,
                io_lane_out_2_6,
                io_lane_out_2_7,
                io_stage_out_1_0,
                io_stage_out_1_1,
                io_stage_out_1_2,
                io_stage_out_1_3,
                io_stage_out_1_4,
                io_stage_out_1_5,
                io_accum_out_0,
                io_accum_out_1,
                io_accum_out_2,
                io_accum_out_3,
                io_accum_out_4,
                io_accum_out_5,
                io_accum_out_6,
                io_accum_out_7,
                io_accum_out_8,
                io_accum_out_9,
                io_accum_out_10,
                io_accum_out_11,
                io_accum_out_12,
                io_accum_out_13,
                io_accum_out_14,
                io_accum_out_15,
                io_accum_out_16,
                io_accum_out_17,
                io_accum_out_18,
                io_accum_out_19,
                io_accum_out_20,
                io_accum_out_21,
                io_accum_out_22,
                io_accum_out_23,
                io_accum_out_24,
                io_accum_out_25,
                io_accum_out_26,
                io_accum_out_27,
                io_accum_out_28,
                io_accum_out_29,
                io_accum_out_30,
                io_accum_out_31,
                io_accum_out_32,
                io_accum_out_33,
                io_accum_out_34,
                io_accum_out_35,
                io_accum_out_36,
                io_accum_out_37,
                io_accum_out_38,
                io_accum_out_39,
                io_accum_out_40,
                io_accum_out_41,
                io_accum_out_42,
                io_accum_out_43,
                io_accum_out_44,
                io_accum_out_45,
                io_accum_out_46,
                io_accum_out_47
);

  wire [15:0] _cells_46_io_lane_out_1;
  wire [15:0] _cells_46_io_lane_out_2;
  wire [15:0] _cells_45_io_lane_out_1;
  wire [15:0] _cells_45_io_lane_out_2;
  wire [15:0] _cells_44_io_lane_out_1;
  wire [15:0] _cells_44_io_lane_out_2;
  wire [15:0] _cells_43_io_lane_out_1;
  wire [15:0] _cells_43_io_lane_out_2;
  wire [15:0] _cells_42_io_lane_out_1;
  wire [15:0] _cells_42_io_lane_out_2;
  wire [15:0] _cells_41_io_stage_out_1;
  wire [15:0] _cells_40_io_lane_out_1;
  wire [15:0] _cells_40_io_lane_out_2;
  wire [15:0] _cells_40_io_stage_out_1;
  wire [15:0] _cells_39_io_lane_out_1;
  wire [15:0] _cells_39_io_lane_out_2;
  wire [15:0] _cells_39_io_stage_out_1;
  wire [15:0] _cells_38_io_lane_out_1;
  wire [15:0] _cells_38_io_lane_out_2;
  wire [15:0] _cells_38_io_stage_out_1;
  wire [15:0] _cells_37_io_lane_out_1;
  wire [15:0] _cells_37_io_lane_out_2;
  wire [15:0] _cells_37_io_stage_out_1;
  wire [15:0] _cells_36_io_lane_out_1;
  wire [15:0] _cells_36_io_lane_out_2;
  wire [15:0] _cells_36_io_stage_out_1;
  wire [15:0] _cells_35_io_stage_out_1;
  wire [15:0] _cells_34_io_lane_out_1;
  wire [15:0] _cells_34_io_lane_out_2;
  wire [15:0] _cells_34_io_stage_out_1;
  wire [15:0] _cells_33_io_lane_out_1;
  wire [15:0] _cells_33_io_lane_out_2;
  wire [15:0] _cells_33_io_stage_out_1;
  wire [15:0] _cells_32_io_lane_out_1;
  wire [15:0] _cells_32_io_lane_out_2;
  wire [15:0] _cells_32_io_stage_out_1;
  wire [15:0] _cells_31_io_lane_out_1;
  wire [15:0] _cells_31_io_lane_out_2;
  wire [15:0] _cells_31_io_stage_out_1;
  wire [15:0] _cells_30_io_lane_out_1;
  wire [15:0] _cells_30_io_lane_out_2;
  wire [15:0] _cells_30_io_stage_out_1;
  wire [15:0] _cells_29_io_stage_out_1;
  wire [15:0] _cells_28_io_lane_out_1;
  wire [15:0] _cells_28_io_lane_out_2;
  wire [15:0] _cells_28_io_stage_out_1;
  wire [15:0] _cells_27_io_lane_out_1;
  wire [15:0] _cells_27_io_lane_out_2;
  wire [15:0] _cells_27_io_stage_out_1;
  wire [15:0] _cells_26_io_lane_out_1;
  wire [15:0] _cells_26_io_lane_out_2;
  wire [15:0] _cells_26_io_stage_out_1;
  wire [15:0] _cells_25_io_lane_out_1;
  wire [15:0] _cells_25_io_lane_out_2;
  wire [15:0] _cells_25_io_stage_out_1;
  wire [15:0] _cells_24_io_lane_out_1;
  wire [15:0] _cells_24_io_lane_out_2;
  wire [15:0] _cells_24_io_stage_out_1;
  wire [15:0] _cells_23_io_stage_out_1;
  wire [15:0] _cells_22_io_lane_out_1;
  wire [15:0] _cells_22_io_lane_out_2;
  wire [15:0] _cells_22_io_stage_out_1;
  wire [15:0] _cells_21_io_lane_out_1;
  wire [15:0] _cells_21_io_lane_out_2;
  wire [15:0] _cells_21_io_stage_out_1;
  wire [15:0] _cells_20_io_lane_out_1;
  wire [15:0] _cells_20_io_lane_out_2;
  wire [15:0] _cells_20_io_stage_out_1;
  wire [15:0] _cells_19_io_lane_out_1;
  wire [15:0] _cells_19_io_lane_out_2;
  wire [15:0] _cells_19_io_stage_out_1;
  wire [15:0] _cells_18_io_lane_out_1;
  wire [15:0] _cells_18_io_lane_out_2;
  wire [15:0] _cells_18_io_stage_out_1;
  wire [15:0] _cells_17_io_stage_out_1;
  wire [15:0] _cells_16_io_lane_out_1;
  wire [15:0] _cells_16_io_lane_out_2;
  wire [15:0] _cells_16_io_stage_out_1;
  wire [15:0] _cells_15_io_lane_out_1;
  wire [15:0] _cells_15_io_lane_out_2;
  wire [15:0] _cells_15_io_stage_out_1;
  wire [15:0] _cells_14_io_lane_out_1;
  wire [15:0] _cells_14_io_lane_out_2;
  wire [15:0] _cells_14_io_stage_out_1;
  wire [15:0] _cells_13_io_lane_out_1;
  wire [15:0] _cells_13_io_lane_out_2;
  wire [15:0] _cells_13_io_stage_out_1;
  wire [15:0] _cells_12_io_lane_out_1;
  wire [15:0] _cells_12_io_lane_out_2;
  wire [15:0] _cells_12_io_stage_out_1;
  wire [15:0] _cells_11_io_stage_out_1;
  wire [15:0] _cells_10_io_lane_out_1;
  wire [15:0] _cells_10_io_lane_out_2;
  wire [15:0] _cells_10_io_stage_out_1;
  wire [15:0] _cells_9_io_lane_out_1;
  wire [15:0] _cells_9_io_lane_out_2;
  wire [15:0] _cells_9_io_stage_out_1;
  wire [15:0] _cells_8_io_lane_out_1;
  wire [15:0] _cells_8_io_lane_out_2;
  wire [15:0] _cells_8_io_stage_out_1;
  wire [15:0] _cells_7_io_lane_out_1;
  wire [15:0] _cells_7_io_lane_out_2;
  wire [15:0] _cells_7_io_stage_out_1;
  wire [15:0] _cells_6_io_lane_out_1;
  wire [15:0] _cells_6_io_lane_out_2;
  wire [15:0] _cells_6_io_stage_out_1;
  wire [15:0] _cells_5_io_stage_out_1;
  wire [15:0] _cells_4_io_lane_out_1;
  wire [15:0] _cells_4_io_lane_out_2;
  wire [15:0] _cells_4_io_stage_out_1;
  wire [15:0] _cells_3_io_lane_out_1;
  wire [15:0] _cells_3_io_lane_out_2;
  wire [15:0] _cells_3_io_stage_out_1;
  wire [15:0] _cells_2_io_lane_out_1;
  wire [15:0] _cells_2_io_lane_out_2;
  wire [15:0] _cells_2_io_stage_out_1;
  wire [15:0] _cells_1_io_lane_out_1;
  wire [15:0] _cells_1_io_lane_out_2;
  wire [15:0] _cells_1_io_stage_out_1;
  wire [15:0] _cells_0_io_lane_out_1;
  wire [15:0] _cells_0_io_lane_out_2;
  wire [15:0] _cells_0_io_stage_out_1;
  cell_0 cells_0 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (io_lane_in_1_0),
    .io_lane_in_2         (io_lane_in_2_0),
    .io_stage_in_1        (io_stage_in_1_0),
    .io_cell_mode         (io_cell_mode_0),
    .io_lane_out_1_select (io_lane_out_1_select_0),
    .io_lane_out_1        (_cells_0_io_lane_out_1),
    .io_lane_out_2        (_cells_0_io_lane_out_2),
    .io_stage_out_1       (_cells_0_io_stage_out_1),
    .io_accum_out         (io_accum_out_0)
  );
  cell_0 cells_1 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (io_select_0 ? _cells_6_io_lane_out_1 : _cells_0_io_lane_out_1),
    .io_lane_in_2         (_cells_0_io_lane_out_2),
    .io_stage_in_1        (io_stage_in_1_1),
    .io_cell_mode         (io_cell_mode_1),
    .io_lane_out_1_select (io_lane_out_1_select_1),
    .io_lane_out_1        (_cells_1_io_lane_out_1),
    .io_lane_out_2        (_cells_1_io_lane_out_2),
    .io_stage_out_1       (_cells_1_io_stage_out_1),
    .io_accum_out         (io_accum_out_1)
  );
  cell_0 cells_2 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1
      (io_select_1 ? _cells_13_io_lane_out_1 : _cells_1_io_lane_out_1),
    .io_lane_in_2         (_cells_1_io_lane_out_2),
    .io_stage_in_1        (io_stage_in_1_2),
    .io_cell_mode         (io_cell_mode_2),
    .io_lane_out_1_select (io_lane_out_1_select_2),
    .io_lane_out_1        (_cells_2_io_lane_out_1),
    .io_lane_out_2        (_cells_2_io_lane_out_2),
    .io_stage_out_1       (_cells_2_io_stage_out_1),
    .io_accum_out         (io_accum_out_2)
  );
  cell_0 cells_3 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1
      (io_select_2 ? _cells_26_io_lane_out_1 : _cells_2_io_lane_out_1),
    .io_lane_in_2         (_cells_2_io_lane_out_2),
    .io_stage_in_1        (io_stage_in_1_3),
    .io_cell_mode         (io_cell_mode_3),
    .io_lane_out_1_select (io_lane_out_1_select_3),
    .io_lane_out_1        (_cells_3_io_lane_out_1),
    .io_lane_out_2        (_cells_3_io_lane_out_2),
    .io_stage_out_1       (_cells_3_io_stage_out_1),
    .io_accum_out         (io_accum_out_3)
  );
  cell_0 cells_4 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_3_io_lane_out_1),
    .io_lane_in_2         (_cells_3_io_lane_out_2),
    .io_stage_in_1        (io_stage_in_1_4),
    .io_cell_mode         (io_cell_mode_4),
    .io_lane_out_1_select (io_lane_out_1_select_4),
    .io_lane_out_1        (_cells_4_io_lane_out_1),
    .io_lane_out_2        (_cells_4_io_lane_out_2),
    .io_stage_out_1       (_cells_4_io_stage_out_1),
    .io_accum_out         (io_accum_out_4)
  );
  cell_0 cells_5 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_4_io_lane_out_1),
    .io_lane_in_2         (_cells_4_io_lane_out_2),
    .io_stage_in_1        (io_stage_in_1_5),
    .io_cell_mode         (io_cell_mode_5),
    .io_lane_out_1_select (io_lane_out_1_select_5),
    .io_lane_out_1        (io_lane_out_1_0),
    .io_lane_out_2        (io_lane_out_2_0),
    .io_stage_out_1       (_cells_5_io_stage_out_1),
    .io_accum_out         (io_accum_out_5)
  );
  cell_0 cells_6 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (io_lane_in_1_1),
    .io_lane_in_2         (io_lane_in_2_1),
    .io_stage_in_1        (_cells_0_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_6),
    .io_lane_out_1_select (io_lane_out_1_select_6),
    .io_lane_out_1        (_cells_6_io_lane_out_1),
    .io_lane_out_2        (_cells_6_io_lane_out_2),
    .io_stage_out_1       (_cells_6_io_stage_out_1),
    .io_accum_out         (io_accum_out_6)
  );
  cell_0 cells_7 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_6_io_lane_out_1),
    .io_lane_in_2         (_cells_6_io_lane_out_2),
    .io_stage_in_1        (_cells_1_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_7),
    .io_lane_out_1_select (io_lane_out_1_select_7),
    .io_lane_out_1        (_cells_7_io_lane_out_1),
    .io_lane_out_2        (_cells_7_io_lane_out_2),
    .io_stage_out_1       (_cells_7_io_stage_out_1),
    .io_accum_out         (io_accum_out_7)
  );
  cell_0 cells_8 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_7_io_lane_out_1),
    .io_lane_in_2         (_cells_7_io_lane_out_2),
    .io_stage_in_1        (_cells_2_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_8),
    .io_lane_out_1_select (io_lane_out_1_select_8),
    .io_lane_out_1        (_cells_8_io_lane_out_1),
    .io_lane_out_2        (_cells_8_io_lane_out_2),
    .io_stage_out_1       (_cells_8_io_stage_out_1),
    .io_accum_out         (io_accum_out_8)
  );
  cell_0 cells_9 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_8_io_lane_out_1),
    .io_lane_in_2         (_cells_8_io_lane_out_2),
    .io_stage_in_1        (_cells_3_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_9),
    .io_lane_out_1_select (io_lane_out_1_select_9),
    .io_lane_out_1        (_cells_9_io_lane_out_1),
    .io_lane_out_2        (_cells_9_io_lane_out_2),
    .io_stage_out_1       (_cells_9_io_stage_out_1),
    .io_accum_out         (io_accum_out_9)
  );
  cell_0 cells_10 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_9_io_lane_out_1),
    .io_lane_in_2         (_cells_9_io_lane_out_2),
    .io_stage_in_1        (_cells_4_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_10),
    .io_lane_out_1_select (io_lane_out_1_select_10),
    .io_lane_out_1        (_cells_10_io_lane_out_1),
    .io_lane_out_2        (_cells_10_io_lane_out_2),
    .io_stage_out_1       (_cells_10_io_stage_out_1),
    .io_accum_out         (io_accum_out_10)
  );
  cell_0 cells_11 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_10_io_lane_out_1),
    .io_lane_in_2         (_cells_10_io_lane_out_2),
    .io_stage_in_1        (_cells_5_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_11),
    .io_lane_out_1_select (io_lane_out_1_select_11),
    .io_lane_out_1        (io_lane_out_1_1),
    .io_lane_out_2        (io_lane_out_2_1),
    .io_stage_out_1       (_cells_11_io_stage_out_1),
    .io_accum_out         (io_accum_out_11)
  );
  cell_0 cells_12 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (io_lane_in_1_2),
    .io_lane_in_2         (io_lane_in_2_2),
    .io_stage_in_1        (_cells_6_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_12),
    .io_lane_out_1_select (io_lane_out_1_select_12),
    .io_lane_out_1        (_cells_12_io_lane_out_1),
    .io_lane_out_2        (_cells_12_io_lane_out_2),
    .io_stage_out_1       (_cells_12_io_stage_out_1),
    .io_accum_out         (io_accum_out_12)
  );
  cell_0 cells_13 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1
      (io_select_3 ? _cells_18_io_lane_out_1 : _cells_12_io_lane_out_1),
    .io_lane_in_2         (_cells_12_io_lane_out_2),
    .io_stage_in_1        (_cells_7_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_13),
    .io_lane_out_1_select (io_lane_out_1_select_13),
    .io_lane_out_1        (_cells_13_io_lane_out_1),
    .io_lane_out_2        (_cells_13_io_lane_out_2),
    .io_stage_out_1       (_cells_13_io_stage_out_1),
    .io_accum_out         (io_accum_out_13)
  );
  cell_0 cells_14 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_13_io_lane_out_1),
    .io_lane_in_2         (_cells_13_io_lane_out_2),
    .io_stage_in_1        (_cells_8_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_14),
    .io_lane_out_1_select (io_lane_out_1_select_14),
    .io_lane_out_1        (_cells_14_io_lane_out_1),
    .io_lane_out_2        (_cells_14_io_lane_out_2),
    .io_stage_out_1       (_cells_14_io_stage_out_1),
    .io_accum_out         (io_accum_out_14)
  );
  cell_0 cells_15 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_14_io_lane_out_1),
    .io_lane_in_2         (_cells_14_io_lane_out_2),
    .io_stage_in_1        (_cells_9_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_15),
    .io_lane_out_1_select (io_lane_out_1_select_15),
    .io_lane_out_1        (_cells_15_io_lane_out_1),
    .io_lane_out_2        (_cells_15_io_lane_out_2),
    .io_stage_out_1       (_cells_15_io_stage_out_1),
    .io_accum_out         (io_accum_out_15)
  );
  cell_0 cells_16 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_15_io_lane_out_1),
    .io_lane_in_2         (_cells_15_io_lane_out_2),
    .io_stage_in_1        (_cells_10_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_16),
    .io_lane_out_1_select (io_lane_out_1_select_16),
    .io_lane_out_1        (_cells_16_io_lane_out_1),
    .io_lane_out_2        (_cells_16_io_lane_out_2),
    .io_stage_out_1       (_cells_16_io_stage_out_1),
    .io_accum_out         (io_accum_out_16)
  );
  cell_0 cells_17 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_16_io_lane_out_1),
    .io_lane_in_2         (_cells_16_io_lane_out_2),
    .io_stage_in_1        (_cells_11_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_17),
    .io_lane_out_1_select (io_lane_out_1_select_17),
    .io_lane_out_1        (io_lane_out_1_2),
    .io_lane_out_2        (io_lane_out_2_2),
    .io_stage_out_1       (_cells_17_io_stage_out_1),
    .io_accum_out         (io_accum_out_17)
  );
  cell_0 cells_18 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (io_lane_in_1_3),
    .io_lane_in_2         (io_lane_in_2_3),
    .io_stage_in_1        (_cells_12_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_18),
    .io_lane_out_1_select (io_lane_out_1_select_18),
    .io_lane_out_1        (_cells_18_io_lane_out_1),
    .io_lane_out_2        (_cells_18_io_lane_out_2),
    .io_stage_out_1       (_cells_18_io_stage_out_1),
    .io_accum_out         (io_accum_out_18)
  );
  cell_0 cells_19 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_18_io_lane_out_1),
    .io_lane_in_2         (_cells_18_io_lane_out_2),
    .io_stage_in_1        (_cells_13_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_19),
    .io_lane_out_1_select (io_lane_out_1_select_19),
    .io_lane_out_1        (_cells_19_io_lane_out_1),
    .io_lane_out_2        (_cells_19_io_lane_out_2),
    .io_stage_out_1       (_cells_19_io_stage_out_1),
    .io_accum_out         (io_accum_out_19)
  );
  cell_0 cells_20 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_19_io_lane_out_1),
    .io_lane_in_2         (_cells_19_io_lane_out_2),
    .io_stage_in_1        (_cells_14_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_20),
    .io_lane_out_1_select (io_lane_out_1_select_20),
    .io_lane_out_1        (_cells_20_io_lane_out_1),
    .io_lane_out_2        (_cells_20_io_lane_out_2),
    .io_stage_out_1       (_cells_20_io_stage_out_1),
    .io_accum_out         (io_accum_out_20)
  );
  cell_0 cells_21 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_20_io_lane_out_1),
    .io_lane_in_2         (_cells_20_io_lane_out_2),
    .io_stage_in_1        (_cells_15_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_21),
    .io_lane_out_1_select (io_lane_out_1_select_21),
    .io_lane_out_1        (_cells_21_io_lane_out_1),
    .io_lane_out_2        (_cells_21_io_lane_out_2),
    .io_stage_out_1       (_cells_21_io_stage_out_1),
    .io_accum_out         (io_accum_out_21)
  );
  cell_0 cells_22 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_21_io_lane_out_1),
    .io_lane_in_2         (_cells_21_io_lane_out_2),
    .io_stage_in_1        (_cells_16_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_22),
    .io_lane_out_1_select (io_lane_out_1_select_22),
    .io_lane_out_1        (_cells_22_io_lane_out_1),
    .io_lane_out_2        (_cells_22_io_lane_out_2),
    .io_stage_out_1       (_cells_22_io_stage_out_1),
    .io_accum_out         (io_accum_out_22)
  );
  cell_0 cells_23 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_22_io_lane_out_1),
    .io_lane_in_2         (_cells_22_io_lane_out_2),
    .io_stage_in_1        (_cells_17_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_23),
    .io_lane_out_1_select (io_lane_out_1_select_23),
    .io_lane_out_1        (io_lane_out_1_3),
    .io_lane_out_2        (io_lane_out_2_3),
    .io_stage_out_1       (_cells_23_io_stage_out_1),
    .io_accum_out         (io_accum_out_23)
  );
  cell_0 cells_24 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (io_lane_in_1_4),
    .io_lane_in_2         (io_lane_in_2_4),
    .io_stage_in_1        (_cells_18_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_24),
    .io_lane_out_1_select (io_lane_out_1_select_24),
    .io_lane_out_1        (_cells_24_io_lane_out_1),
    .io_lane_out_2        (_cells_24_io_lane_out_2),
    .io_stage_out_1       (_cells_24_io_stage_out_1),
    .io_accum_out         (io_accum_out_24)
  );
  cell_0 cells_25 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1
      (io_select_4 ? _cells_30_io_lane_out_1 : _cells_24_io_lane_out_1),
    .io_lane_in_2         (_cells_24_io_lane_out_2),
    .io_stage_in_1        (_cells_19_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_25),
    .io_lane_out_1_select (io_lane_out_1_select_25),
    .io_lane_out_1        (_cells_25_io_lane_out_1),
    .io_lane_out_2        (_cells_25_io_lane_out_2),
    .io_stage_out_1       (_cells_25_io_stage_out_1),
    .io_accum_out         (io_accum_out_25)
  );
  cell_0 cells_26 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1
      (io_select_5 ? _cells_37_io_lane_out_1 : _cells_25_io_lane_out_1),
    .io_lane_in_2         (_cells_25_io_lane_out_2),
    .io_stage_in_1        (_cells_20_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_26),
    .io_lane_out_1_select (io_lane_out_1_select_26),
    .io_lane_out_1        (_cells_26_io_lane_out_1),
    .io_lane_out_2        (_cells_26_io_lane_out_2),
    .io_stage_out_1       (_cells_26_io_stage_out_1),
    .io_accum_out         (io_accum_out_26)
  );
  cell_0 cells_27 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_26_io_lane_out_1),
    .io_lane_in_2         (_cells_26_io_lane_out_2),
    .io_stage_in_1        (_cells_21_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_27),
    .io_lane_out_1_select (io_lane_out_1_select_27),
    .io_lane_out_1        (_cells_27_io_lane_out_1),
    .io_lane_out_2        (_cells_27_io_lane_out_2),
    .io_stage_out_1       (_cells_27_io_stage_out_1),
    .io_accum_out         (io_accum_out_27)
  );
  cell_0 cells_28 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_27_io_lane_out_1),
    .io_lane_in_2         (_cells_27_io_lane_out_2),
    .io_stage_in_1        (_cells_22_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_28),
    .io_lane_out_1_select (io_lane_out_1_select_28),
    .io_lane_out_1        (_cells_28_io_lane_out_1),
    .io_lane_out_2        (_cells_28_io_lane_out_2),
    .io_stage_out_1       (_cells_28_io_stage_out_1),
    .io_accum_out         (io_accum_out_28)
  );
  cell_0 cells_29 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_28_io_lane_out_1),
    .io_lane_in_2         (_cells_28_io_lane_out_2),
    .io_stage_in_1        (_cells_23_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_29),
    .io_lane_out_1_select (io_lane_out_1_select_29),
    .io_lane_out_1        (io_lane_out_1_4),
    .io_lane_out_2        (io_lane_out_2_4),
    .io_stage_out_1       (_cells_29_io_stage_out_1),
    .io_accum_out         (io_accum_out_29)
  );
  cell_0 cells_30 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (io_lane_in_1_5),
    .io_lane_in_2         (io_lane_in_2_5),
    .io_stage_in_1        (_cells_24_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_30),
    .io_lane_out_1_select (io_lane_out_1_select_30),
    .io_lane_out_1        (_cells_30_io_lane_out_1),
    .io_lane_out_2        (_cells_30_io_lane_out_2),
    .io_stage_out_1       (_cells_30_io_stage_out_1),
    .io_accum_out         (io_accum_out_30)
  );
  cell_0 cells_31 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_30_io_lane_out_1),
    .io_lane_in_2         (_cells_30_io_lane_out_2),
    .io_stage_in_1        (_cells_25_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_31),
    .io_lane_out_1_select (io_lane_out_1_select_31),
    .io_lane_out_1        (_cells_31_io_lane_out_1),
    .io_lane_out_2        (_cells_31_io_lane_out_2),
    .io_stage_out_1       (_cells_31_io_stage_out_1),
    .io_accum_out         (io_accum_out_31)
  );
  cell_0 cells_32 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_31_io_lane_out_1),
    .io_lane_in_2         (_cells_31_io_lane_out_2),
    .io_stage_in_1        (_cells_26_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_32),
    .io_lane_out_1_select (io_lane_out_1_select_32),
    .io_lane_out_1        (_cells_32_io_lane_out_1),
    .io_lane_out_2        (_cells_32_io_lane_out_2),
    .io_stage_out_1       (_cells_32_io_stage_out_1),
    .io_accum_out         (io_accum_out_32)
  );
  cell_0 cells_33 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_32_io_lane_out_1),
    .io_lane_in_2         (_cells_32_io_lane_out_2),
    .io_stage_in_1        (_cells_27_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_33),
    .io_lane_out_1_select (io_lane_out_1_select_33),
    .io_lane_out_1        (_cells_33_io_lane_out_1),
    .io_lane_out_2        (_cells_33_io_lane_out_2),
    .io_stage_out_1       (_cells_33_io_stage_out_1),
    .io_accum_out         (io_accum_out_33)
  );
  cell_0 cells_34 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_33_io_lane_out_1),
    .io_lane_in_2         (_cells_33_io_lane_out_2),
    .io_stage_in_1        (_cells_28_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_34),
    .io_lane_out_1_select (io_lane_out_1_select_34),
    .io_lane_out_1        (_cells_34_io_lane_out_1),
    .io_lane_out_2        (_cells_34_io_lane_out_2),
    .io_stage_out_1       (_cells_34_io_stage_out_1),
    .io_accum_out         (io_accum_out_34)
  );
  cell_0 cells_35 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_34_io_lane_out_1),
    .io_lane_in_2         (_cells_34_io_lane_out_2),
    .io_stage_in_1        (_cells_29_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_35),
    .io_lane_out_1_select (io_lane_out_1_select_35),
    .io_lane_out_1        (io_lane_out_1_5),
    .io_lane_out_2        (io_lane_out_2_5),
    .io_stage_out_1       (_cells_35_io_stage_out_1),
    .io_accum_out         (io_accum_out_35)
  );
  cell_0 cells_36 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (io_lane_in_1_6),
    .io_lane_in_2         (io_lane_in_2_6),
    .io_stage_in_1        (_cells_30_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_36),
    .io_lane_out_1_select (io_lane_out_1_select_36),
    .io_lane_out_1        (_cells_36_io_lane_out_1),
    .io_lane_out_2        (_cells_36_io_lane_out_2),
    .io_stage_out_1       (_cells_36_io_stage_out_1),
    .io_accum_out         (io_accum_out_36)
  );
  cell_0 cells_37 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1
      (io_select_6 ? _cells_42_io_lane_out_1 : _cells_36_io_lane_out_1),
    .io_lane_in_2         (_cells_36_io_lane_out_2),
    .io_stage_in_1        (_cells_31_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_37),
    .io_lane_out_1_select (io_lane_out_1_select_37),
    .io_lane_out_1        (_cells_37_io_lane_out_1),
    .io_lane_out_2        (_cells_37_io_lane_out_2),
    .io_stage_out_1       (_cells_37_io_stage_out_1),
    .io_accum_out         (io_accum_out_37)
  );
  cell_0 cells_38 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_37_io_lane_out_1),
    .io_lane_in_2         (_cells_37_io_lane_out_2),
    .io_stage_in_1        (_cells_32_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_38),
    .io_lane_out_1_select (io_lane_out_1_select_38),
    .io_lane_out_1        (_cells_38_io_lane_out_1),
    .io_lane_out_2        (_cells_38_io_lane_out_2),
    .io_stage_out_1       (_cells_38_io_stage_out_1),
    .io_accum_out         (io_accum_out_38)
  );
  cell_0 cells_39 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_38_io_lane_out_1),
    .io_lane_in_2         (_cells_38_io_lane_out_2),
    .io_stage_in_1        (_cells_33_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_39),
    .io_lane_out_1_select (io_lane_out_1_select_39),
    .io_lane_out_1        (_cells_39_io_lane_out_1),
    .io_lane_out_2        (_cells_39_io_lane_out_2),
    .io_stage_out_1       (_cells_39_io_stage_out_1),
    .io_accum_out         (io_accum_out_39)
  );
  cell_0 cells_40 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_39_io_lane_out_1),
    .io_lane_in_2         (_cells_39_io_lane_out_2),
    .io_stage_in_1        (_cells_34_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_40),
    .io_lane_out_1_select (io_lane_out_1_select_40),
    .io_lane_out_1        (_cells_40_io_lane_out_1),
    .io_lane_out_2        (_cells_40_io_lane_out_2),
    .io_stage_out_1       (_cells_40_io_stage_out_1),
    .io_accum_out         (io_accum_out_40)
  );
  cell_0 cells_41 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_40_io_lane_out_1),
    .io_lane_in_2         (_cells_40_io_lane_out_2),
    .io_stage_in_1        (_cells_35_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_41),
    .io_lane_out_1_select (io_lane_out_1_select_41),
    .io_lane_out_1        (io_lane_out_1_6),
    .io_lane_out_2        (io_lane_out_2_6),
    .io_stage_out_1       (_cells_41_io_stage_out_1),
    .io_accum_out         (io_accum_out_41)
  );
  cell_0 cells_42 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (io_lane_in_1_7),
    .io_lane_in_2         (io_lane_in_2_7),
    .io_stage_in_1        (_cells_36_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_42),
    .io_lane_out_1_select (io_lane_out_1_select_42),
    .io_lane_out_1        (_cells_42_io_lane_out_1),
    .io_lane_out_2        (_cells_42_io_lane_out_2),
    .io_stage_out_1       (io_stage_out_1_0),
    .io_accum_out         (io_accum_out_42)
  );
  cell_0 cells_43 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_42_io_lane_out_1),
    .io_lane_in_2         (_cells_42_io_lane_out_2),
    .io_stage_in_1        (_cells_37_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_43),
    .io_lane_out_1_select (io_lane_out_1_select_43),
    .io_lane_out_1        (_cells_43_io_lane_out_1),
    .io_lane_out_2        (_cells_43_io_lane_out_2),
    .io_stage_out_1       (io_stage_out_1_1),
    .io_accum_out         (io_accum_out_43)
  );
  cell_0 cells_44 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_43_io_lane_out_1),
    .io_lane_in_2         (_cells_43_io_lane_out_2),
    .io_stage_in_1        (_cells_38_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_44),
    .io_lane_out_1_select (io_lane_out_1_select_44),
    .io_lane_out_1        (_cells_44_io_lane_out_1),
    .io_lane_out_2        (_cells_44_io_lane_out_2),
    .io_stage_out_1       (io_stage_out_1_2),
    .io_accum_out         (io_accum_out_44)
  );
  cell_0 cells_45 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_44_io_lane_out_1),
    .io_lane_in_2         (_cells_44_io_lane_out_2),
    .io_stage_in_1        (_cells_39_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_45),
    .io_lane_out_1_select (io_lane_out_1_select_45),
    .io_lane_out_1        (_cells_45_io_lane_out_1),
    .io_lane_out_2        (_cells_45_io_lane_out_2),
    .io_stage_out_1       (io_stage_out_1_3),
    .io_accum_out         (io_accum_out_45)
  );
  cell_0 cells_46 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_45_io_lane_out_1),
    .io_lane_in_2         (_cells_45_io_lane_out_2),
    .io_stage_in_1        (_cells_40_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_46),
    .io_lane_out_1_select (io_lane_out_1_select_46),
    .io_lane_out_1        (_cells_46_io_lane_out_1),
    .io_lane_out_2        (_cells_46_io_lane_out_2),
    .io_stage_out_1       (io_stage_out_1_4),
    .io_accum_out         (io_accum_out_46)
  );
  cell_0 cells_47 (
    .clock                (clock),
    .reset                (reset),
    .io_lane_in_1         (_cells_46_io_lane_out_1),
    .io_lane_in_2         (_cells_46_io_lane_out_2),
    .io_stage_in_1        (_cells_41_io_stage_out_1),
    .io_cell_mode         (io_cell_mode_47),
    .io_lane_out_1_select (io_lane_out_1_select_47),
    .io_lane_out_1        (io_lane_out_1_7),
    .io_lane_out_2        (io_lane_out_2_7),
    .io_stage_out_1       (io_stage_out_1_5),
    .io_accum_out         (io_accum_out_47)
  );
endmodule


6.3.0
